name: 'Hello World Dopcker Action'
description: 'Say hello to a user or the entire world'
inputs:
  who-to-greet:
    description: 'Who would you link to greet'
    required: true
    default: 'world'
  output:
    time: 
      description: 'The time we said hello to the user"
  runs:
    using: docker
    image: 'Dockerfile'
    args:
      - ${{ inputs.who-to-greet }}
