name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 06 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: Ubuntu-latest
    steps:
      - run: |
          echo "This job was triggered by the event: ${{ github.event_name }}
          echo "The current branch is ${{ github.ref }} of the repository ${{ github.respository }}"
      - uses: actions/checkout@v6.0.2

      - name: List all the files in the repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Test:
    runs-on: Ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
    - run: echo "Testing..."
  Load-Test:
    runs-on: Ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
    - run: |
        echo "Testing..."
        sleep 15
  
  Production:
    runs-on: Ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'production'
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 10
      - run: |
          echo "🚀 Step 2..."
          sleep 10
      - run: |
          echo "🚀 Step 3..."
          sleep 10
      - run: |
          echo "🚀 Step 4..."
          sleep 10
      - run: |
          echo "🚀 Step 5..."
          sleep 10
